### ISSUE TITLE
Some DRAIN templates with <*> do not have parameters extracted

### ISSUE THREAD

**Issue by mohammedayub44** [logpai/Drain3#80]
Hi,
I'm trying to parse about 25 Mil log records from a logging system to create a template repository and extract variables for all of them. 
While troubleshooting I see that some templates , do not return parameters. Is this a drain training issue ?

They are like below - 

Log - 
`mcpd[5006]: 01070638:5: Pool /Common/cib_seamservices-prod-crl.jpmchase.net_443 member /Common/cib_icpcarl04317.svr.us.jpmchase.net_197:20202 monitor status down. [ /Common/https_get_seamservices-prod-crl.jpmchase.net: down; last error: /Common/https_get_seamservices-prod-crl.jpmchase.net: Response Code: 200 @2023/03/26 00:02:52. ] [ was up for 23hrs:58mins:16sec ]`

Template - 
`mcpd<::>: <: NUM_ID :>: Pool <: <:*:> <: JPMC_NET_ID :> member <: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <: <:*:> <:*:> <:*:> <:*:> Response Code: <:NUM:> @<:NUM:><: UNIX_FOLDER_PATH :> <: NUM_ID :>. ] [ was up for <:*:> ]`

Extracted Variables - `None`

These are the params I have used for DRAIN:
<python>
```

[MASKING]
masking = [   
{"regex_pattern":"\\[\\d+\\]", "mask_with": ""},
{"regex_pattern":"(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\:\\d+|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})", "mask_with": " IP"},
{"regex_pattern":"(\\/[\\w\\/]+\\.[\\w{2,10}]+)", "mask_with": " UNIX_FILE_PATH "},
{"regex_pattern":"(\\/[\\w\\/]+)", "mask_with": " UNIX_FOLDER_PATH "},
{"regex_pattern":"(0[xX][0-9a-fA-F]+)", "mask_with": " HEXADECIMAL "},
{"regex_pattern":"([0-9a-zA-Z]{15,})", "mask_with": " ALPHANUM_ID "},
{"regex_pattern":"(\\d+(:\\d+)+)", "mask_with": " NUM_ID "},
{"regex_pattern":"(\\d+:(\\d+)*)", "mask_with": " NUM_ID "},
{"regex_pattern":"(?i)pid(\\s+|\\S)\\d+", "mask_with": " PID_ID "},
{"regex_pattern":"(?i)user(\\s+|\\S)\\d+", "mask_with": " USER_ID "},
{"regex_pattern":"(?i)user\\S+", "mask_with": " USER_ID "},
{"regex_pattern":"(?i)(\\S*jpmchase\\S*net\\S*)", "mask_with": " JPMC_NET_ID "},
{"regex_pattern":"(?i)tmm[0-9]*", "mask_with": " tmm "},
{"regex_pattern":"(?i)(\\S*session\\s{0,1}\\S{0,1}\\s{0,1}\\d*)", "mask_with": " SESSION_ID "},
{"regex_pattern":"((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$)", "mask_with": "NUM"}
] 
mask_prefix = <:
mask_suffix = :>

[DRAIN]
sim_th = 0.3
depth = 4
max_children = 400
#max_clusters = 150
#extra_delimiters = ["_"]

[PROFILING]
enabled = True
report_sec = 30

```

Appreciate any help

**Comment by Superskyyy** [comment]
Indeed, that is one of the minor problems of the base implementation. This is due to the calculation of similarity is considering already masked tokens/tokens with digits in its numerator during calculation(this makes two logs have a overestimated similarity therefore making everything <*>. 

As a current workaround before I merge a fix for this, you can either first clone the repo and try the new Jaccard drain which uses a different and more robust similarity calculation or go to the code base to change the similarity distance method of drain.py to remove the known (mask tokens) from the calculation. 

In the near future(next month?), we will implement a dynamic threshold (no longer 0.3/0.4 for everyone) which effectively solve this problem.

**Comment by mohammedayub44** [comment]
Thanks so much for confirming. I'll wait for you fix. Meantime I'll try the JaccardDrain as well.

**Comment by mohammedayub44** [comment]
@Superskyyy what would be best way to install the clone version to try the JaccardDrain. I'm trying to use it inside my Jupyter notebook.

**Comment by mohammedayub44** [comment]
Looks like part of the issue was, me giving overlapping regexes and spaces in the masked values.
I had to re-validate all the regexes to check if two regexes are not replacing the same string. Also removed the spaces in the masked values which was treating the mask prefix/suffixes as token during similarity calculation. 

Parse tree depth plays an important factor for the number of <*> you want in your templates. I was able to avoid unnecessary groupings by increasing the depth of tree. Finding a correct balance between no. of templates and  however, is all trial and error with multiple iterations for now.

Also, for one of the templates  which did not have any `<*>` , did not return any variables. This is a strange one, I'm yet to find was is the cause for this (it happened for both JaccardDrain and Drain)

Log: `kernel: Hardware name: F5 Networks C119/PCA-0408-05 REV A  , BIOS OBJ: OBJ-0645-xx BIOS: 5.20.030.0 ME: 6.0.50.1252 05/06/2019`

Template:  `kernel: Hardware name: F5 Networks C119/PCA-<:NUM:>-<:NUM:> REV A , BIOS OBJ: OBJ-<:NUM:>-xx BIOS: <:IP:> ME: <:IP:><:NUM:> <:NUM:>/<:NUM:>/<:NUM:>`

Vars: ` [''] `

**Comment by Impelon** [comment]
I'll chime in here this discussion as the updated parameter extraction algorithm was contributed by myself.

The parameter extraction actually works by creating a regex from a given template, and matching that regex to the given log entry. In case the regex and the given log entry do not match, `None` will be returned.
As mentioned in https://github.com/logpai/Drain3/pull/67#issuecomment-1296178531, this will not work correctly if e.g. the template contains more parameters than can be found in the actual log entry, meaning that `JaccardDrain` should actually probably not be used when parameter extraction is important.

Regardless, you can actually inspect the regex created by this mechanism by calling `_get_template_parameter_extraction_regex` on a `TemplateMiner` directly. 
<details>
<summary>Let's look at why the matching fails with your original template (I've set `exact_matching=False` to make the regex more readable).</summary>
```python3
>>> miner = TemplateMiner()
>>> template = "mcpd<::>: <: NUM_ID :>: Pool <: <:*:> <: JPMC_NET_ID :> member <: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <: <:*:> <:*:> <:*:> <:*:> Response Code: <:NUM:> @<:NUM:><: UNIX_FOLDER_PATH :> <: NUM_ID :>. ] [ was up for <:*:> ]"
>>> entry = "mcpd[5006]: 01070638:5: Pool /Common/cib_seamservices-prod-crl.jpmchase.net_443 member /Common/cib_icpcarl04317.svr.us.jpmchase.net_197:20202 monitor status down. [ /Common/https_get_seamservices-prod-crl.jpmchase.net: down; last error: /Common/https_get_seamservices-prod-crl.jpmchase.net: Response Code: 200 @2023/03/26 00:02:52. ] [ was up for 23hrs:58mins:16sec ]"
>>> miner._get_template_parameter_extraction_regex(template, False)
('^mcpd(?P<p_0>.+?):\\s+(?P<p_6>.+?):\\s+Pool\\s+<:\\s+(?P<p_10>.+?)\\s+(?P<p_2>.+?)\\s+member\\s+<:\\s+(?P<p_11>.+?)\\s+(?P<p_12>.+?)\\s+(?P<p_13>.+?)\\s+(?P<p_14>.+?)\\s+(?P<p_15>.+?)\\s+(?P<p_16>.+?)\\s+(?P<p_17>.+?)\\s+(?P<p_18>.+?)\\s+(?P<p_19>.+?)\\s+(?P<p_20>.+?)\\s+(?P<p_21>.+?)\\s+(?P<p_22>.+?)\\s+(?P<p_23>.+?)\\s+(?P<p_24>.+?)\\s+(?P<p_25>.+?)\\s+(?P<p_26>.+?)\\s+(?P<p_27>.+?)\\s+(?P<p_28>.+?)\\s+<:\\s+(?P<p_29>.+?)\\s+(?P<p_30>.+?)\\s+(?P<p_31>.+?)\\s+(?P<p_32>.+?)\\s+Response\\s+Code:\\s+(?P<p_36>.+?)\\s+@(?P<p_37>.+?)(?P<p_43>.+?)\\s+(?P<p_7>.+?)\\.\\s+\\]\\s+\\[\\s+was\\s+up\\s+for\\s+(?P<p_33>.+?)\\s+\\]$', {'p_0': '', 'p_1': '', 'p_2': ' JPMC_NET_ID ', 'p_3': ' JPMC_NET_ID ', 'p_4': ' tmm ', 'p_5': ' IP', 'p_6': ' NUM_ID ', 'p_7': ' NUM_ID ', 'p_8': ' NUM_ID ', 'p_9': ' ALPHANUM_ID ', 'p_10': '*', 'p_11': '*', 'p_12': '*', 'p_13': '*', 'p_14': '*', 'p_15': '*', 'p_16': '*', 'p_17': '*', 'p_18': '*', 'p_19': '*', 'p_20': '*', 'p_21': '*', 'p_22': '*', 'p_23': '*', 'p_24': '*', 'p_25': '*', 'p_26': '*', 'p_27': '*', 'p_28': '*', 'p_29': '*', 'p_30': '*', 'p_31': '*', 'p_32': '*', 'p_33': '*', 'p_34': '*', 'p_35': ' PID_ID ', 'p_36': 'NUM', 'p_37': 'NUM', 'p_38': 'NUM', 'p_39': ' UNIX_FILE_PATH ', 'p_40': ' USER_ID ', 'p_41': ' HEXADECIMAL ', 'p_42': ' SESSION_ID ', 'p_43': ' UNIX_FOLDER_PATH ', 'p_44': ' UNIX_FOLDER_PATH '})
```
This regex is quite hard to read, so I simplified it:
`mcpd.+?: .+?: Pool <: .+? .+? member <: .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? .+? <: .+? .+? .+? .+? Response Code: .+? @.+?.+? .+?\. \] \[ was up for .+? \]`
This obviously does not match, because `<:` is not included in the original log entry. But this problem is already present in the constructed log template, so the extraction algorithm cannot construct a meaningful pattern here.
</details>

I'd agree that the overlapping regexes probably caused the bad template in the first case. Keep in mind, the extraction algorithm is independent from Drain/JaccardDrain and actually is solely based upon the matching patterns in your config and the provided template.
Ok, let's also look at your more recent example.
```python3
>>> miner = TemplateMiner()
>>> entry = "kernel: Hardware name: F5 Networks C119/PCA-0408-05 REV A  , BIOS OBJ: OBJ-0645-xx BIOS: 5.20.030.0 ME: 6.0.50.1252 05/06/2019"
>>> template = "kernel: Hardware name: F5 Networks C119/PCA-<:NUM:>-<:NUM:> REV A , BIOS OBJ: OBJ-<:NUM:>-xx BIOS: <:IP:> ME: <:IP:><:NUM:> <:NUM:>/<:NUM:>/<:NUM:>"
>>> miner._get_template_parameter_extraction_regex(template, True)
('^kernel:\\s+Hardware\\s+name:\\s+F5\\s+Networks\\s+C119/PCA\\-(?P<p_10>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))\\-(?P<p_11>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))\\s+REV\\s+A\\s+,\\s+BIOS\\s+OBJ:\\s+OBJ\\-(?P<p_12>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))\\-xx\\s+BIOS:\\s+(?P<p_3>(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\:\\d+|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}))\\s+ME:\\s+(?P<p_4>(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\:\\d+|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}))(?P<p_13>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))\\s+(?P<p_14>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))/(?P<p_15>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))/(?P<p_16>((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$))$', {'p_0': '', 'p_1': 'ALPHANUM_ID', 'p_2': 'JPMC_NET_ID', 'p_3': 'IP', 'p_4': 'IP', 'p_5': 'IP', 'p_6': 'HEXADECIMAL', 'p_7': 'USER_ID', 'p_8': '*', 'p_9': 'tmm', 'p_10': 'NUM', 'p_11': 'NUM', 'p_12': 'NUM', 'p_13': 'NUM', 'p_14': 'NUM', 'p_15': 'NUM', 'p_16': 'NUM', 'p_17': 'NUM', 'p_18': 'UNIX_FOLDER_PATH', 'p_19': 'PID_ID', 'p_20': 'UNIX_FILE_PATH', 'p_21': 'NUM_ID', 'p_22': 'SESSION_ID'})
>>> # The resulting regex is again quite complicated, mostly because in needs to include the appropriate matching patterns for all 9 parameters. So see what went wrong I try removing parts of the regex until it matches part of the entry.
>>> re.match(r"kernel:\s+Hardware\s+name:\s+F5\s+Networks\s+C119/PCA\-(?P<p_10>((?<=[^A-Za-z0-9])|^)([\-\+]?\d+)((?=[^A-Za-z0-9])|$))\-(?P<p_11>((?<=[^A-Za-z0-9])|^)([\-\+]?\d+)((?=[^A-Za-z0-9])|$))\s+REV\s+A\s+,\s+BIOS\s+OBJ:\s+OBJ\-(?P<p_12>((?<=[^A-Za-z0-9])|^)([\-\+]?\d+)((?=[^A-Za-z0-9])|$))\-xx\s+BIOS:\s+(?P<p_3>(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\:\d+|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))\s+ME:\s+(?P<p_4>(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\:\d+|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))", entry)
<re.Match object; span=(0, 114), match='kernel: Hardware name: F5 Networks C119/PCA-0408->
>>> _.groupdict()
{'p_10': '0408', 'p_11': '05', 'p_12': '0645', 'p_3': '5.20.030.0', 'p_4': '6.0.50.125'}
>>> # everything up until ME: <:IP:> works.
```
The last part does not work however. `ME: <:IP:><:NUM:>` does not match `ME: 6.0.50.1252`. This is because of the way you have defined your `NUM` regex:
`((?<=[^A-Za-z0-9])|^)([\-\+]?\d+)` (part of it) Here you say that a number cannot be proceeded by another number.
This will work during the creation of the template though, because drain will first replace IPs to produce the template, so when the template is constructed `ME: <:IP:>2` is what template creator sees, and here it is fine to transform this into `ME: <:IP:><:NUM:>` because 2 is not proceeded by a number.
So this indeed results in a template that the extraction algorithm does not want to match with the given log entry.
It will match it if you use `exact_matching=False`, where the regexes are ignored for extracting parameters:
```python3
>>> miner.extract_parameters(template, entry, False)
[ExtractedParameter(value='0408', mask_name='NUM'), ExtractedParameter(value='05', mask_name='NUM'), ExtractedParameter(value='0645', mask_name='NUM'), ExtractedParameter(value='5.20.030.0', mask_name='IP'), ExtractedParameter(value='6', mask_name='IP'), ExtractedParameter(value='.0.50.1252', mask_name='NUM'), ExtractedParameter(value='05', mask_name='NUM'), ExtractedParameter(value='06', mask_name='NUM'), ExtractedParameter(value='2019', mask_name='NUM')]
```
But this is not optimal, because the extracted parameter for IP is now not what you'd expect.

Unfortunately there is not much one can do to change the behaviour of the parameter extraction in this case, the way you defined `NUM` does not permit creating a regex that will match `ME: 6.0.50.1252` with  `ME: <:IP:><:NUM:>` .
Yes, one valid critisism of the the parameter extraction algorithm is that it is overly reliant upon the user defining appropriate regexes.

I'd suggest redefining the regexes to solve this specific problem. Here are some ideas:
1.  One crude way to solve it would be to add a rule for specifically this case where a number can follow an IP. (Yes you can define multiple patterns for the same mask.)
 ``
{"regex_pattern":"((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$)", "mask_with": "NUM"},
{"regex_pattern":"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$)", "mask_with": "NUM"}
```
2. Is the template really meant to be `ME: <:IP:><:NUM:>`? This is probably a special case where this is actually a version number and not an IP, right? You could write a new regex for version numbers. You also have to redefine IP so it does not allow another number directly following it.
```
{"regex_pattern":"\\d{1,3}(\\.\d{1,3}){3}(:\d+)?(?!\d)", "mask_with": "IP"}
{"regex_pattern":"\\d+(\\.\d+){3,}", "mask_with": "VERSION"}
```
3. You can redefine `NUM` to be more lax about the characters that can come before it. Specifically it should be fine if numbers have other digits around them; normally they are part of the number anyway.
```
{"regex_pattern":"((?<=[^A-Za-z])|^)([-+]?\\d+)((?=[^A-Za-z])|$)", "mask_with": "NUM"}
```

I think you should prefer solution 2 or 3 if they do not break anything else, they make the most sense to me.

**Comment by mohammedayub44** [comment]
@Impelon  Sorry for the late reply on this. 
Firstly, thanks for the in-detail explanation of how the extract parameter logic works. It clearly makes sense now. I used solution 2 to rewrite the regexes so it does not allow any overlap and it seemed to work smooth. 
Appreciate you jumping in to clarify, I will go ahead and close this for now.

**Comment by 0ptimista** [comment]
> @mohammedayub44事实上，这是基础实现的小问题之一。这是因为相似度的计算在计算过程中考虑了已经屏蔽的标记/分子中带有数字的标记（这使得两个日志具有高估的相似度，因此使得一切<*>。
> 
> 作为当前的解决方法，在我合并此问题的修复程序之前，您可以首先克隆存储库并尝试新的 Jaccard Drain，它使用不同且更强大的相似性计算，或者转到代码库来更改 Drain.py 的相似性距离方法从计算中删除已知的（掩码标记）。
> 
> 在不久的将来（下个月？），我们将实现原作者在一篇较新的论文中提出的动态阈值技术（不再是所有人的0.3/0.4），有效解决这个问题。

Hi is there a plan date for publish a new version on PyPI?  Some thing has changed sinced last published version on 2022

**Comment by 0ptimista** [comment]
> @mohammedayub44 Indeed, that is one of the minor problems of the base implementation. This is due to the calculation of similarity is considering already masked tokens/tokens with digits in its numerator during calculation(this makes two logs have a overestimated similarity therefore making everything <*>.
> 
> As a current workaround before I merge a fix for this, you can either first clone the repo and try the new Jaccard drain which uses a different and more robust similarity calculation or go to the code base to change the similarity distance method of drain.py to remove the known (mask tokens) from the calculation.
> 
> In the near future(next month?), we will implement a dynamic threshold technique that was proposed by the original authors in a newer paper (no longer 0.3/0.4 for everyone) which effectively solve this problem.

Hi is there a plan date for publish a new version on PyPI? Some thing has changed sinced last published version on 2022

**Comment by Superskyyy** [comment]
> > @mohammedayub44 Indeed, that is one of the minor problems of the base implementation. This is due to the calculation of similarity is considering already masked tokens/tokens with digits in its numerator during calculation(this makes two logs have a overestimated similarity therefore making everything <*>.
> 
> > 
> 
> > As a current workaround before I merge a fix for this, you can either first clone the repo and try the new Jaccard drain which uses a different and more robust similarity calculation or go to the code base to change the similarity distance method of drain.py to remove the known (mask tokens) from the calculation.
> 
> > 
> 
> > In the near future(next month?), we will implement a dynamic threshold technique that was proposed by the original authors in a newer paper (no longer 0.3/0.4 for everyone) which effectively solve this problem.
> 
> 
> 
> Hi is there a plan date for publish a new version on PyPI? Some thing has changed since last published version on 2022

hello, yes a new version will be published once the latest PR gets pushed. ETA at the end of this week.
